FROM node:lts-alpine

ARG FRONTITY_NAME
ARG FRONTITY_DEV_PORT
ARG FRONTITY_BUILD_DEVELOPMENT

RUN mkdir -p usr/src/app
WORKDIR /usr/src/app
COPY ${FRONTITY_NAME} .
RUN npm install
EXPOSE ${FRONTITY_DEV_PORT}
CMD ["npx", "frontity", "dev"]